# Generated by Django 3.1 on 2020-08-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cow_Say_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cow_Say_What',
            new_name='Cow_Say_What_Model',
        ),
    ]
