# Generated by Django 3.1 on 2020-08-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cow_Say_App', '0002_auto_20200818_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow_say_what_model',
            name='cow_output',
            field=models.TextField(default=''),
        ),
    ]
